### ISSUE TITLE
Improve TIA WSYNC emulation

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#42]
The attached test ROM illustrates how it can tell if it was run on an emulator or a real console.  Obviously, the emulator should identify as a real console too.
[emubug.zip](https://github.com/DirtyHairy/stella/files/661923/emubug.zip)

**Comment by thrust26** [comment]
Old core says 2600. :)

**Comment by sa666666** [comment]
This is fixed in https://github.com/DirtyHairy/stella/commit/a6bc2478526ef4768c6372d03b86d7296fe09d9b.  

I actually knew how to fix this issue when I created the issue, but I wanted it documented here anyway.  It was actually fixed in the old core in 2006 (!), documented below:

https://sourceforge.net/p/stella/mailman/stella-commits/thread/E1GIcL6-0006fP-OL@sc8-pr-cvs8.sourceforge.net/

**Comment by DirtyHairy** [comment]
2006 --- an anagram of 2600 :smirk: I am well aware of the issue; however, I fail to see how this fix gets closer to accurately emulating it. Afaik, what happens on WSYNC is that the TIA pulls low RDY which will cause the CPU to halt on the **next** read cycle. However, this change (as well as the implementation in the old core) checks whether the **previous** cycle was a ready cycle. In addition, it will skip WSYNC alltogether, while the real thing should continue executing just until it hits a read cycle.

**Comment by sa666666** [comment]
By all means, please feel free to change it to more accurately emulate what's going on.  The implementation in the old core fixes the ROM in question, but it's probably only a superficial change.

I assume you did this differently in 6502.ts; how did you fix the issue there?

**Comment by DirtyHairy** [comment]
I didn't fix it at all :smiley: In 6502.ts, CPU emulation is currently not sophisticated enough to do anything like this. In particular, all reads required for decoding the instruction happen in the first cycle, and all reads and writes required by the instruction itself happen in the last cycle (this is the reason while Pole Position is glitched in 6502.ts). As the CPU in 6502.ts is dispatched cycle by cycle, properly emulating memory access patterns would require turning every instruction into a state machine. Doing this would make the implementation of this particular twist trivial, but the required changes are pretty invasive.

I am not sure about Stella; the fact that dispatch is driven by the CPU makes emulating memory access patterns much easier. I think one way to correctly implement RDY behavior would be to signal the TIA on each read access. WSYNC could then raise an internal flag, and the necessery advance of the system clock could happen on the next read signal. I might take a stab at implementing this at some point.

However, I guess I would first have to design a valid testcase that fails on the current implementation and validate this on real hardware.

**Comment by sa666666** [comment]
Since this isn't really fixed but only worked around, we should reopen the bug.

**Comment by KarolS** [comment]
Isn't it the same mechanism VIC-II uses to stop 6510 in Commodore 64? Maybe a look into how C64 emulators do it would help.

**Comment by sa666666** [comment]
Yes, that's a good idea.  The main problem now is lack of time; I hope to revisit this soon.

**Comment by DirtyHairy** [comment]
@sa666666 if you like I can take over this, I think I have a pretty solid idea of how to test and implement proper RDY handling :smirk:

**Comment by sa666666** [comment]
Yes, of course if you have time and are willing, I won't complain :smile: I'm working on the PAL colour-loss now, and how to have it ready in the next day or so.  Also I plan to do a new release by the end of the month.  So feel free to work on any issue you like before then.

**Comment by DirtyHairy** [comment]
New release sounds good, I guess we are closing in on 5.0 final :smile: I am currently still trying to get meaningful profiling data out of Stella. After that, I'll be looking at RDY.

@KarolS I don't know the details of the C64, but I guess that's true. In fact, afaik every 6502 based system that implements DMA uses this mechanims to make the 6502 temporarily relinquish the bus.

**Comment by DirtyHairy** [comment]
This [testcase](https://github.com/stella-emu/stella/files/1027425/testcase.zip) probes for proper emulation of the CPU RDY line. You can switch the testcase between PAL and NTSC with the color switc. On Stella, the result looks like this:

![rdy](https://cloud.githubusercontent.com/assets/2444224/26428572/c2ac6506-40e2-11e7-9bdb-28c32c270a5a.png)

Observe the "nose" in the middle of the white bar --- this is due to the aforementioned difference in the color clock when stopping the TIA on the first write fof a RMW instruction (INC in this case) instead of stopping at the next read cycle. On real hardware, there is no "nose", just a smooth white rectangle.

Other emulators that don't try to account for proper RDY behavior at all show a series of black stripes instead of the "nose" (javatari, MESS). 6502.ts is special: it displays properly, but this is not because of proper RDY emulation, but rather because it doesn't emulate the first spurious write in a RMW instruction at all (that's 6502ts/6502.ts#51) :smirk:

Next step: fix it.

**Comment by DirtyHairy** [comment]
Correct screenshot:

![rdy_1](https://cloud.githubusercontent.com/assets/2444224/26515150/2c645aee-4278-11e7-9b1c-d9b9143b1d7a.png)
